### ISSUE TITLE
Get token

### ISSUE THREAD

**Issue by hoanglongutc** [ee02217/homeassistant-mi-heater#5]
I just bought a heater: zhimi-heater-zb1_mibt3C8F and use MiHome version 5.9.19
Do you have instructions to help me get device tokens
thank you very much

**Comment by hoanglongutc** [comment]
> I just bought a heater: zhimi-heater-zb1_mibt3C8F and use MiHome version 5.9.19
> Do you have instructions to help me get device tokens
> thank you very much

I did it. Thank you very much for this contribution

**Comment by hilaring** [comment]
@hoanglongutc how did you get the token??
